<a href="https://colab.research.google.com/github/dhyan95/Self-Learning-Python-Journey/blob/main/Python_journal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

12/12/25 - Basics of Python

In [ ]:
#First day - Pg.65 - 100
#tuple is an immutable, fixed length sequence
tup = (4,5,6,'string')
tup

(4, 5, 6, 'string')

In [ ]:
tup1 = tuple('string')
tup1

('s', 't', 'r', 'i', 'n', 'g')

In [ ]:
nested_tuple = (4,5,6),(8,9)
nested_tuple[1]

(8, 9)

In [ ]:
#lists are mutable and variable length sequence
list1 = ["lists"]
list1

['lists']

In [ ]:
list1.append("dwarf")
list1

['lists', 'dwarf']

In [ ]:
list1.insert(0,'hello')
list1

['hello', 'lists', 'dwarf']

In [ ]:
list1.pop(2)
list1

['hello', 'lists']

In [ ]:
list1.remove("lists")
list1

['hello']

In [ ]:
"hello" in list1 #can also use not in

True

In [ ]:
#concatenating and combining
[4,None,"foo"]+[1,2,3]

[4, None, 'foo', 1, 2, 3]

In [ ]:
#sorting
a=[7,4,5,2]
a.sort()  #for characters use sort(key=len)
a

[2, 4, 5, 7]

In [ ]:
#slicing
seq = (3,4,5,6,7,3,1,2,4,7,8)
seq[1:5]  #seq[:5];seq[3:]

(4, 5, 6, 7)

In [ ]:
#reversing a tuple
reversed_seq = seq[::-1]
reversed_seq

(8, 7, 4, 2, 1, 3, 7, 6, 5, 4, 3)

In [ ]:
#dictionary - it stores key value pairs use this instead of hashmaps?
d1 = {"a":"hello","b":[1,2,3]}
d1
#for inserting,accessing,setting same as tuple or list
#del for delete
#update for appending

{'a': 'hello', 'b': [1, 2, 3]}

In [ ]:
#set is an unordered collection of unique elements
a={1,2,3,1,2,3}
a

{1, 2, 3}

In [ ]:
a1 = {1,2,3,4}
b1 = {3,4,5,6}
#union function
a1.union(b1) #a1 | b1

{1, 2, 3, 4, 5, 6}

In [ ]:
#intersection
a1.intersection(b1) #a1 & b1
#refer table 3.1 page 78

{3, 4}

In [ ]:
#built in sequence functions

#sorted([3,2,1]) function
#reversed() function

In [ ]:
#functions
def func():
  return "greet"
print(func())

greet


In [ ]:
def profile(name,age):
  print(name,age)
profile(name="Dhyan",age=21)

Dhyan 21


In [ ]:
#for loop
fruits = ['apple','banana','mango']
for f in fruits:
  print(f,len(f))

apple 5
banana 6
mango 5


In [ ]:
#looping through a dictionary
student = {"name":"dhyan","age":21}
for key,value in student.items():
  print(key,":",value)

name : dhyan
age : 21


In [ ]:
count = 1
while count <= 5:
  print(count)
  count+=1

1
2
3
4
5


In [ ]:
#sum of a list using a function and loop
listt = [2,3,3,5,6]
def sum_list():
  sum = 0
  for i in listt:
    sum+=i
  return sum
print(sum_list())

19


In [ ]:
#remove duplicates from a list - convert it to set
con_set = set(listt)
print(con_set)

{2, 3, 5, 6}


In [ ]:
#word counter
list_word = ["Hello","How","Are","You"]
def word_counter():
  count = 0
  for l in list_word:
    count+=1
  return count
print(word_counter())

4


EDGE QUESTIONS

In [ ]:
if 0.2+0.3==0.5:
  print("true")
else:
  print("false")

true


In [ ]:
print("/\\/\\/\\")

/\/\/\


12/13/25 NUMPY - https://numpy.org/devdocs/user/absolute_beginners.html#

In [ ]:
import numpy as np
arr = np.array(range(0,10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(10,30,5)   #np.arange(10,30)

array([10, 15, 20, 25])

In [ ]:
np.zeros((3,4,7))   #np.ones((3,4,7)) as the name suggests

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
np.linspace(10,30,5)  #for float numbers

array([10., 15., 20., 25., 30.])

ADDING, REMOVING AND SORTING

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.delete(x,1)

array([1, 3])

How to convert a 1D array into a 2D array

In [ ]:
x.shape

(3,)

In [ ]:
x1 = x[np.newaxis, :]  #for column vector [:, np.newaxis]
x1.shape

(1, 3)

BASIC OPERATIONS

In [ ]:
a = np.random.rand(2,2)
a

array([[0.85128575, 0.97931424],
       [0.51569511, 0.52348119]])

In [ ]:
b = np.array([(1,2),(3,4)])
b

array([[1, 2],
       [3, 4]])

In [ ]:
#addition
c = a+b
c

array([[1.85128575, 2.97931424],
       [3.51569511, 4.52348119]])

In [ ]:
#sqaure
b**2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
#matrix multiplication
a@b

array([[3.78922848, 5.61982847],
       [2.08613868, 3.12531498]])

In [ ]:
a<0.1

array([[False, False],
       [False, False]])

INDEXING, SLICING, ITERATING

In [ ]:
arr[5]

np.int64(5)

In [ ]:
arr[3:5]

array([3, 4])

In [ ]:
#reversed
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr[::3] #first colon means beginning of the array, the second means end of the array and the number 3 is the step value

array([0, 3, 6, 9])

VSTACK, HSTACK

In [ ]:
a1 = np.array([(1,2,3),(4,5,6)])
a2 = np.array([(7,8,9),(10,11,12)])

In [ ]:
np.concatenate((a1,a2),axis=1)  #for vstack axis=0

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((a1,a2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

BROADCASTING - operations on arrays of different sizes

In [ ]:
x1*1.6

array([[1.6, 3.2, 4.8]])

Reshaping and flattening multidimensional arrays

In [ ]:
x

array([1, 2, 3])

In [ ]:
a1 = x.flatten()  #changes to new array wont affect the parent array
a1

array([1, 2, 3])

In [ ]:
a1.ravel() #opposite of flatten

array([1, 2, 3])

CALCULUS / STATISTICS FUNCTIONS

In [ ]:
a10 = 2*np.random.rand(1000) + 10
a10

array([11.16280838, 10.57072797, 11.10884919, 10.87094591, 11.85587249,
       10.28860099, 11.61229851, 11.96599246, 11.67676556, 10.50982802,
       10.29269775, 10.79413422, 11.66563118, 11.92583148, 11.91020272,
       10.58763172, 11.78133289, 10.65283306, 10.98152821, 11.35413725,
       10.17084317, 10.13688515, 11.51176826, 10.50778735, 10.247568  ,
       10.80269499, 11.91552314, 11.24574747, 10.09340938, 10.94085287,
       10.45072289, 11.91890175, 11.77824475, 11.39620437, 10.75704409,
       11.97188974, 11.37987839, 10.72579895, 11.66291753, 11.54640952,
       11.36709723, 10.4561794 , 10.53727429, 10.41508916, 10.23782365,
       11.10083446, 11.9627982 , 11.33068081, 10.6920924 , 11.0880867 ,
       10.44789305, 10.68585405, 11.38755808, 11.79656423, 10.68340284,
       10.08696049, 11.79087396, 10.86917608, 10.62845952, 10.41554703,
       11.69157985, 10.00159821, 11.84553922, 10.68703544, 10.60354166,
       11.762251  , 11.60050923, 10.85837723, 10.38468415, 11.94

In [ ]:
np.mean(a10)

np.float64(11.01105551015013)

In [ ]:
np.std(a10)

np.float64(0.5773268433815831)

In [ ]:
np.percentile(a10,80)  #80% of numbers are less than 11.62

np.float64(11.583723592869822)

In [ ]:
import numpy as np

a = np.arange(10)
b = a[2:8]
b[:] = -1

print(a)

[ 0  1 -1 -1 -1 -1 -1 -1  8  9]


Sales Data Analysis
You have daily sales data for a small store for a month (30 days) stored as a list:

In [ ]:
sales = [200, 220, 250, 180, 210, 240, 230, 260, 200, 190, 220, 210, 250, 270, 300, 310, 290, 280, 260, 270, 300, 320, 310, 300, 290, 280, 270, 260, 250, 240]

#Convert this list into a NumPy array.
sales_arr = np.array(sales)
print("Sales Array:", sales_arr)

#Compute the average sales, maximum sales, and minimum sales.
print("Average sales:", np.average(sales_arr))
print("Maximum sales:", np.max(sales_arr))
print("Minimum sales:", np.min(sales_arr))

#Find the days when sales exceeded 280.
high_sales_days = sales_arr[sales_arr > 280]
print('Sales that exceeded 280:', high_sales_days)

Sales Array: [200 220 250 180 210 240 230 260 200 190 220 210 250 270 300 310 290 280
 260 270 300 320 310 300 290 280 270 260 250 240]
Average sales: 255.33333333333334
Maximum sales: 320
Minimum sales: 180
Sales that exceeded 280: [300 310 290 300 320 310 300 290]


Temperature Monitoring
A city records hourly temperatures in Celsius over a week (7 days × 24 hours = 168 readings) as a NumPy array called temps.

In [ ]:
#Convert the temperatures to Fahrenheit.
temps_cel = np.random.rand(168) + 30
temps_cel

temps_fah = (temps_cel - 30)*2
temps_fah

#Identify the coldest day and the hottest day based on daily averages.
print("Coldest day in fahrenheit, my arse is freezing: ",np.min(temps_fah))
print("Hottest day in fahrenheit: ",np.max(temps_fah))

#Find all hours when the temperature was below 0°C.
below = temps_fah[temps_fah<0.6]
print("Hours when the temperature was below 0°C: ",below)

Coldest day in fahrenheit, my arse is freezing:  0.007269097505691491
Hottest day in fahrenheit:  1.9916439062722517
Hours when the temperature was below 0°C:  [0.53810835 0.38252039 0.41265181 0.38849119 0.49346879 0.59654791
 0.5888888  0.53810128 0.39143899 0.48742571 0.07520324 0.26456826
 0.18643513 0.36071901 0.03087186 0.0072691  0.33820037 0.5064703
 0.16912684 0.37511568 0.30989395 0.13194383 0.52106184 0.35648752
 0.51796911 0.55730293 0.41769822 0.30322892 0.32989033 0.54448003
 0.35283348 0.08037167 0.40134526 0.56805311 0.02182456 0.03982412
 0.39707263 0.03911806 0.49164808 0.43700847 0.40305387 0.46099637
 0.07498053 0.40757253 0.01424155 0.29077897 0.35863377 0.33097614
 0.1261156  0.43679301 0.52278526]


Class Grades
You have grades for 5 students in 4 subjects as a NumPy array:

In [ ]:
grades = np.array([
 [85, 90, 78, 92],
 [70, 75, 80, 72],
 [88, 82, 91, 85],
 [60, 65, 58, 62],
 [95, 92, 88, 96]
])

#Compute each student’s average grade.
student1_average = np.average(grades[0])
print("Student 1: ",student1_average)
student2_average = np.average(grades[1])
print("Student 2: ",student2_average)
student3_average = np.average(grades[2])
print("Student 3: ",student3_average)
student4_average = np.average(grades[3])
print("Student 4: ",student4_average)

#Find the subject with the highest average score.
subject1_average = np.average(grades[:,0])
print("Subject 1: ",subject1_average)

#Identify students scoring above 90 in at least 2 subjects.
above_90_counts = np.sum(grades > 90, axis=1)
students_above_90 = np.where(above_90_counts >= 2)[0]
print("Students scoring above 90 in at least 2 subjects:", students_above_90)

Student 1:  86.25
Student 2:  74.25
Student 3:  86.5
Student 4:  61.25
Subject 1:  79.6
Students scoring above 90 in at least 2 subjects: [4]


FOCUS ON VECTORS

1) Temperature Alerts

In [ ]:
temp = np.random.rand(365,24) + 30
temp

#Identify all days where the temperature exceeded 35°C for more than 5 hours.
hot_hours = temp>30.9
hot_hours_count = np.sum(hot_hours,axis=1)
hot_days = np.where(hot_hours_count>5)[0]
hot_days

array([ 51,  58, 108, 176, 222])

2) Sales Performance

In [ ]:
sale = np.random.rand(12,6) + (3000-1000)
sale

#Find products whose average quarterly sales exceeded 500.
quaterly = sale/4
quaterly
product_qua = np.where(np.average(quaterly,axis=0)>500.123)[0]
product_qua

#Identify months where all products had sales above 2000.
all_products = np.all(sale>2000,axis=0)
all_products

array([ True,  True,  True,  True,  True,  True])

3) Exam Score Analysis

In [ ]:
scores = np.random.rand(10,5) + 80    #students vs subjects
scores

#Identify students who scored above 80 in all subjects.
top_students = np.where(np.all(scores > 80, axis=1))[0]
top_students

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12/15/25 - LINEAR ALGEBRA WITH NumPy

Dot product - same as inner product

In [ ]:
import numpy as np
np.dot([3j+0,5j+2],[2j+5,1j+2])

np.complex128(-7+27j)

Vdot - same syntax as dot, unlike dot it flattens the array into a 1D array and then performs the operations.
Not as powerful as vecdot

Multi Dot

In [ ]:
from numpy.linalg import multi_dot
A = np.random.rand(100,100)
B = np.random.rand(100,10)
C = np.random.rand(10,100)
multi_dot([A,B,C])

array([[ 93.81988685,  90.15826175, 111.64068586, ...,  95.62507554,
        145.27295986, 131.58308908],
       [101.18216021,  96.65961011, 119.65369491, ..., 102.75394375,
        154.74604838, 139.84660959],
       [ 81.35500204,  78.18359948,  95.8811673 , ...,  82.24809432,
        124.5661389 , 112.89556145],
       ...,
       [ 90.12769187,  87.93996769, 108.2109811 , ...,  91.21050162,
        138.59122027, 128.17009422],
       [ 90.05451915,  87.13511598, 110.03072372, ...,  92.06754106,
        140.93111444, 127.27373507],
       [ 92.20404783,  89.22326699, 109.26987206, ...,  93.1767656 ,
        139.56353342, 129.09122257]])

VecDot - working with multiple arrays and when one wants to use broadcasting functions on arrays. Very similar to linalg.vecdot - for specifying explicitly that this is a linear algebra function

In [ ]:
v = np.array([(0., 5., 0.), [0., 0., 10.], [0., 6., 8.]])
n = np.array([0., 0.6, 0.8])
np.vecdot(v, n)

array([ 3.,  8., 10.])

Tensor dot

In [ ]:
a_0 = np.array([[1, 2], [3, 4]])
b_0 = np.array([[5, 6], [7, 8]])
c_0 = np.tensordot(a_0,b_0,axes=0)
c_0

array([[[[ 5,  6],
         [ 7,  8]],

        [[10, 12],
         [14, 16]]],


       [[[15, 18],
         [21, 24]],

        [[20, 24],
         [28, 32]]]])

12/17/25 - Pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s = pd.Series([1,2,3,4,5,np.nan])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
dtype: float64

In [ ]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df

A         B         C         D
2013-01-01 -0.225419 -0.036533 -0.293876  1.271890
2013-01-02  0.033790  0.117220  0.698560  0.682444
2013-01-03  1.821803 -0.177034  1.021230  0.173070
2013-01-04  2.450163  2.788096  0.317884  1.319131
2013-01-05 -0.798649 -0.563820 -0.670127  0.102490
2013-01-06  0.563508  0.469004 -1.867472 -0.435149

In [ ]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [ ]:
df.head()    #df.tail()

A         B         C         D
2013-01-01 -0.225419 -0.036533 -0.293876  1.271890
2013-01-02  0.033790  0.117220  0.698560  0.682444
2013-01-03  1.821803 -0.177034  1.021230  0.173070
2013-01-04  2.450163  2.788096  0.317884  1.319131
2013-01-05 -0.798649 -0.563820 -0.670127  0.102490

In [ ]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.640866  0.432822 -0.132300  0.518979
std    1.254221  1.202809  1.053547  0.698186
min   -0.798649 -0.563820 -1.867472 -0.435149
25%   -0.160617 -0.141909 -0.576064  0.120135
50%    0.298649  0.040343  0.012004  0.427757
75%    1.507229  0.381058  0.603391  1.124528
max    2.450163  2.788096  1.021230  1.319131

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.T     #transpose

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.225419    0.033790    1.821803    2.450163   -0.798649    0.563508
B   -0.036533    0.117220   -0.177034    2.788096   -0.563820    0.469004
C   -0.293876    0.698560    1.021230    0.317884   -0.670127   -1.867472
D    1.271890    0.682444    0.173070    1.319131    0.102490   -0.435149

In [ ]:
df["A"]

2013-01-01   -0.225419
2013-01-02    0.033790
2013-01-03    1.821803
2013-01-04    2.450163
2013-01-05   -0.798649
2013-01-06    0.563508
Freq: D, Name: A, dtype: float64

In [ ]:
df[0:2]

A         B         C         D
2013-01-01 -0.225419 -0.036533 -0.293876  1.271890
2013-01-02  0.033790  0.117220  0.698560  0.682444

Selection by label

In [ ]:
df.loc[dates[0]]

A   -0.225419
B   -0.036533
C   -0.293876
D    1.271890
Name: 2013-01-01 00:00:00, dtype: float64

In [ ]:
#for getting faster access to a scalar
df.at[dates[0],"A"]

np.float64(-0.2254190562132632)

Selection by precise location

In [ ]:
df.iloc[0:2,2:4]

C         D
2013-01-01 -0.293876  1.271890
2013-01-02  0.698560  0.682444

In [ ]:
df.iloc[[1,2,4],[1,3]]

B         D
2013-01-02  0.117220  0.682444
2013-01-03 -0.177034  0.173070
2013-01-05 -0.563820  0.102490

In [ ]:
df[df>0]

A         B         C         D
2013-01-01       NaN       NaN       NaN  1.271890
2013-01-02  0.033790  0.117220  0.698560  0.682444
2013-01-03  1.821803       NaN  1.021230  0.173070
2013-01-04  2.450163  2.788096  0.317884  1.319131
2013-01-05       NaN       NaN       NaN  0.102490
2013-01-06  0.563508  0.469004       NaN       NaN

Missing data

In [ ]:
#df.dropna() - drops any rows having NAN
#df.isna() - gets boolean mask where values are NAN
#df.fillna(value="5") - fills NAN with the specified value

Stats

In [ ]:
df.mean(axis=1)

2013-01-01    0.179015
2013-01-02    0.383004
2013-01-03    0.709767
2013-01-04    1.718819
2013-01-05   -0.482527
2013-01-06   -0.317527
Freq: D, dtype: float64

In [ ]:
#UDF
df.agg(lambda x: np.mean(x)*5.6)

A    3.588850
B    2.423804
C   -0.740880
D    2.906285
dtype: float64

In [ ]:
df.value_counts()

A          B          C          D        
-0.798649  -0.563820  -0.670127   0.102490    1
-0.225419  -0.036533  -0.293876   1.271890    1
 0.033790   0.117220   0.698560   0.682444    1
 0.563508   0.469004  -1.867472  -0.435149    1
 1.821803  -0.177034   1.021230   0.173070    1
 2.450163   2.788096   0.317884   1.319131    1
Name: count, dtype: int64

Merge and join

In [ ]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

In [ ]:
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [ ]:
left

key  lval
0  foo     1
1  foo     2

In [ ]:
right

key  rval
0  foo     4
1  foo     5

In [ ]:
pd.merge(left,right,on="key")

key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [ ]:
df1 = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
df1

A      B         C         D
0  foo    one -0.178765 -0.270368
1  bar    one  0.557334 -0.386380
2  foo    two  0.292196  0.035930
3  bar  three -0.292728 -0.057658
4  foo    two -0.295730 -0.446588
5  bar    two  0.765104 -0.188964
6  foo    one  0.915129 -0.027807
7  foo  three  0.942365 -1.055495

In [ ]:
df1.groupby("A").sum()

B         C         D
A                                         
bar        onethreetwo  1.029711 -0.633002
foo  onetwotwoonethree  1.675195 -1.764328

Re-shaping and Pivot tables

In [ ]:
#pivot
data = {
"value": range(12),
"variable": ["A"] * 3 + ["B"] * 3 + ["C"] * 3 + ["D"] * 3,
"date": pd.to_datetime(["2020-01-03", "2020-01-04", "2020-01-05"] * 4)
}
df = pd.DataFrame(data)
df

value variable       date
0       0        A 2020-01-03
1       1        A 2020-01-04
2       2        A 2020-01-05
3       3        B 2020-01-03
4       4        B 2020-01-04
5       5        B 2020-01-05
6       6        C 2020-01-03
7       7        C 2020-01-04
8       8        C 2020-01-05
9       9        D 2020-01-03
10     10        D 2020-01-04
11     11        D 2020-01-05

In [ ]:
df.pivot(index="date",columns="variable",values="value")

variable    A  B  C   D
date                   
2020-01-03  0  3  6   9
2020-01-04  1  4  7  10
2020-01-05  2  5  8  11

In [ ]:
#pivot_table
import datetime

df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 6,
        "B": ["A", "B", "C"] * 8,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 4,
        "D": np.random.randn(24),
        "E": np.random.randn(24),
        "F": [datetime.datetime(2013, i, 1) for i in range(1, 13)]
        + [datetime.datetime(2013, i, 15) for i in range(1, 13)],
    }
)
df

A  B    C         D         E          F
0     one  A  foo -0.767325 -0.703187 2013-01-01
1     one  B  foo -1.328759  2.195013 2013-02-01
2     two  C  foo -1.156210 -0.105756 2013-03-01
3   three  A  bar -0.746617  0.124638 2013-04-01
4     one  B  bar -0.644942  1.676432 2013-05-01
5     one  C  bar -0.574369 -0.654302 2013-06-01
6     two  A  foo -1.282538 -0.156956 2013-07-01
7   three  B  foo  0.242047  1.228115 2013-08-01
8     one  C  foo -0.896776  0.309501 2013-09-01
9     one  A  bar  1.509975  0.599698 2013-10-01
10    two  B  bar -1.035412 -0.940361 2013-11-01
11  three  C  bar -0.411409  0.784310 2013-12-01
12    one  A  foo  0.920446 -0.135673 2013-01-15
13    one  B  foo -0.629326  0.661686 2013-02-15
14    two  C  foo  0.511177 -0.302517 2013-03-15
15  three  A  bar -1.729163 -0.432173 2013-04-15
16    one  B  bar  0.819589  0.234253 2013-05-15
17    one  C  bar -1.023707  0.717456 2013-06-15
18    two  A  foo -2.417596 -0.875114 2013-07-15
19  three  B  foo  0.020448  0.861627 2013-08-15
20    one  C  foo  1.208870  0.493867 2013-09-15
21    one  A  bar  1.688074  1.238204 2013-10-15
22    two  B  bar  1.254831  0.411587 2013-11-15
23  three  C  bar -1.204995  0.158959 2013-12-15

In [ ]:
df.pivot_table(index=["A","B"],columns=["C"],values="D")

C             bar       foo
A     B                    
one   A  1.599024  0.076561
      B  0.087324 -0.979043
      C -0.799038  0.156047
three A -1.237890       NaN
      B       NaN  0.131248
      C -0.808202       NaN
two   A       NaN -1.850067
      B  0.109710       NaN
      C       NaN -0.322516

In [ ]:
#melt
cheese = pd.DataFrame(
    {
        "first": ["John", "Mary"],
        "last": ["Doe", "Bo"],
        "height": [5.5, 6.0],
        "weight": [130, 150],
    }
)
cheese

first last  height  weight
0  John  Doe     5.5     130
1  Mary   Bo     6.0     150

In [ ]:
cheese = pd.melt(cheese,id_vars=['first',"last"])
cheese

first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

Time series / date functionality

In [ ]:
import datetime

pd.Timestamp(datetime.datetime(2012, 5, 1))
pd.Timestamp('2012-05-01 00:00:00')

Timestamp('2012-05-01 00:00:00')

In [ ]:
pd.Timestamp("2012-05-01")
pd.Timestamp('2012-05-01 00:00:00')

Timestamp('2012-05-01 00:00:00')